#!/bin/bash

# Config
session="bashrc_conf"
location="$HOME"
conf=".bashrc"

wname="bashrc"

# don't recreate
exists=$(tmux list-sessions | grep $session)
if [ "$exists" = "" ]; then
    # Start Session
    tmux new-session -d -s $session

    # Nvim Window
    tmux rename-window -t $wname
    tmux send-keys -t $wname "cd $location" C-m
    tmux send-keys -t $wname "nvim $conf && source $conf" C-m
fi

# Attach
tmux attach-session -t $session:0
