#!/bin/bash

# Config
session="imgscal_conf"
location="$HOME/.config/imgscal/"
conf="config.json"

wname="imgscal"

# don't recreate
exists=$(tmux list-sessions | grep $session)
if [ "$exists" = "" ]; then
    # Start Session
    tmux new-session -d -s $session

    # Nvim Window
    tmux rename-window -t $wname
    tmux send-keys -t $wname "cd $location" C-m
    tmux send-keys -t $wname "nvim $conf" C-m
fi

# Attach
tmux attach-session -t $session:0
