#!/bin/bash

bashdir="$(dirname "${BASH_SOURCE[0]}")"
location="${bashdir}/scripts/"

function search() {
    find $location -type f | sed -e "s|$location|- |"
}

if [[ -z "$1" ]]; then
    # Print list of scripts
    echo
    search
else
    # Find provided script to run
    if [ -f "$location$1" ]; then
        exec "$location$1"
    else
        echo -e "Script: \e[1;31m$1\e[0m not found!"

        # Search for similar script names
        close="$(search | grep $1 --color=always)"
        if [[ ! -z "$close" ]]; then
            echo
            echo "Some possible scripts were found:"
            echo "$close"
        fi
    fi
fi
