#!/bin/bash

bashloc="${BASH_SOURCE[0]}"
if [ -L "$bashloc" ]; then
    bashloc="$(readlink -f "$bashloc")"
fi

location="$(dirname "$bashloc")/scripts/"

RED='\033[31m'
NC='\033[0m'
BOLD='\033[1m'

if [ -z "$1" ]; then
    # fzf selection menu
    result="$(find $location -type f | sed -e "s|$location||" | fzf)"
    exec "$location$result"
else
    if [ -f "$location$1" ]; then
        exec "$location$1"
    else
        # filter scripts using argument
        list="$(find $location -type f | sed -e "s|$location||" | grep $1)"

        if [ -z "$list" ]; then
            echo -e "$RED$BOLD!$NC tsess script not found: $RED$BOLD$1$NC"
            exit 1
        else
            # fzf selection menu on filtered options
            result=$(echo "$list" | fzf)
            exec "$location$result"
        fi
    fi
fi
