#!/bin/bash

# Config
session="aoc2024"
location="$HOME/dev/aoc_2024/"

wname_code="aoc"
wname_py="python"

# don't recreate
exists=$(tmux list-sessions | grep $session)
if [ "$exists" = "" ]; then
    # Start Session
    tmux new-session -d -s $session

    # Code Window
    tmux rename-window -t 0 $wname_code
    tmux send-keys -t $wname_code "cd $location" C-m
    tmux send-keys -t $wname_code "nvim ." C-m

    # Terminal Window
    tmux new-window -t $session:1 -n $wname_py
    tmux send-keys -t $wname_py "cd $location" C-m
    tmux send-keys -t $wname_py "source ./venv/bin/activate" C-m
fi

# Attach
tmux attach-session -t $session:0
