#!/bin/bash

# Config
session="arcremia"
code_location="$HOME/dev/arcremia/"
tools_location="$HOME/dev/arcremia/tools/animation_generator/"
design_location="$HOME/dev/arcremia/design/"
imgscal_location="$HOME/dev/arcremia/tools/imgscal/"

imgscal_config="$HOME/dev/arcremia/tools/imgscal/config.json"

wname_code="gdscript"
wname_tools="tools"
wname_design="design"
wname_imgscal="imgscal"
wname_terminal="terminal"

# don't recreate
exists=$(tmux list-sessions | grep $session)
if [ "$exists" = "" ]; then
    # Start Session
    tmux new-session -d -s $session

    # GDScript Window
    tmux rename-window -t 0 $wname_code
    tmux send-keys -t $wname_code "cd $code_location" C-m
    tmux send-keys -t $wname_code "nvim ." C-m

    # Tool Window
    tmux new-window -t $session:1 -n $wname_tools
    tmux send-keys -t $wname_tools "cd $tools_location" C-m
    tmux send-keys -t $wname_tools "nvim ." C-m

    # Design Window
    tmux new-window -t $session:2 -n $wname_design
    tmux send-keys -t $wname_design "cd $design_location" C-m
    tmux send-keys -t $wname_design "nvim ." C-m

    # Imgscal Window
    tmux new-window -t $session:3 -n $wname_imgscal
    tmux send-keys -t $wname_imgscal "cd $imgscal_location" C-m
    tmux send-keys -t $wname_imgscal "export IMGSCAL_CONFIG=\"$imgscal_config\"" C-m

    # Terminal Running Window
    tmux new-window -t $session:4 -n $wname_terminal
    tmux send-keys -t $wname_terminal "cd $code_location" C-m
    tmux send-keys -t $wname_terminal "export IMGSCAL_CONFIG=\"$imgscal_config\"" C-m
fi

# Attach
tmux attach-session -t $session:0
