#!/bin/bash

# Config
session="pers_empty"
location="~/dev/"

# Don't recreate
exists=$(tmux list-sessions | grep $session)
if ["$exists" = ""]; then
    # Start Session
    tmux new-session -d -s $session

    # Go to personal dev directory
    tmux send-keys -t 0 "cd $location" C-m
fi

# Attach
tmux attach-session -t $session:0
