#!/bin/bash

# Config
session="imgscal"
code_location="$HOME/dev/imgscal/"
data_location="$HOME/imgscal/"

wname_code="imgscal"
wname_data="scripts"
wname_bash="bash"

# don't recreate
exists=$(tmux list-sessions | grep $session)
if [ "$exists" = "" ]; then
    # Start Session
    tmux new-session -d -s $session

    # Code Window
    tmux rename-window -t 0 $wname_code
    tmux send-keys -t $wname_code "cd $code_location" C-m
    tmux send-keys -t $wname_code "nvim ." C-m

    # Data Window
    tmux new-window -t $session:1 -n $wname_data
    tmux send-keys -t $wname_data "cd $data_location" C-m
    tmux send-keys -t $wname_data "nvim ." C-m

    # Bash Window
    tmux new-window -t $session:2 -n $wname_bash
    tmux send-keys -t $wname_bash "cd $code_location" C-m
fi

# Attach
tmux attach-session -t $session:0
